### ISSUE TITLE
Seems like a missing line break/feed here

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#10]
https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L140

It seems like there is a missing "<h:br/> after "Platform." as it displays oddly with what seems like an ended line (since it only has a few words on the line) following immediately by a new paragraph without the normal empty line.

**Comment by jmcdaniels** [comment]
Line added.
