### ISSUE TITLE
PP-Module abbreviation isn't correct

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#12]
On line https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L183

the PP-Module is shown with the abbreviation of "PP" and note "PP-Module". While this "works" technically a PP-Module is not a PP.

**Comment by jmcdaniels** [comment]
Changed to PP-Module
