### ISSUE TITLE
KEK should include more than FEK

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#13]
The KEK may encrypt other KEKs, not just the FEK as shown here in the Technical Terms. https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L287

According to the Key Chaining description (https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L283) any number of layers can be set, so saying a KEK can only encrypt the FEK is in conflict with the Key Chaining description and the intent of the requirements.

**Comment by jmcdaniels** [comment]
Changed to "another key"
