### ISSUE TITLE
Change "AS PP" to "[AppPP]"

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#16]
https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L782-L783

For consistency the reference to the App PP should be consistent, and the [AppPP] is used elsewhere

**Comment by woodbe** [comment]
Another reference, this time "App PP".

https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L821

**Comment by woodbe** [comment]
Another reference, this time to "AS PP"
https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L2279-L2280

**Comment by woodbe** [comment]
Another reference, this time "App PP"
https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L2305

**Comment by woodbe** [comment]
Here is another one where the full name is written out
https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L2678

**Comment by jmcdaniels** [comment]
All references changed to app cite.
