### ISSUE TITLE
Should be "KEKs"

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#19]
https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L878

It seems odd to say "key encrypting keys" and then KEKs immediately in the same sentence. Given that KEK is a defined acronym it should be used here.

**Comment by jmcdaniels** [comment]
Changed references to KEKs.
