### ISSUE TITLE
Applications and drive access

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#20]
Applications are unlikely to have access to the drive and the ability to issue TRIM commands, especially on SSDs. While it may be supported by the OS (in some cases), it is not always available.

https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L973-L978

This, and the above application note assume that access to TRIM is available to the application. While great if possible, depending on how the application or service is written, this may not be the case.

**Comment by jmcdaniels** [comment]
This is just to make sure that an application provides guidance for the proper use with the OE it runs on, not that the application can resolve these issues itself.
