### ISSUE TITLE
Steps aren't actually labeled

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#22]
https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L1018

This states if "step 3 fails" yet the steps are not labeled, so it could cause confusion.

Similar in 

https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L1006 where steps are not actually labeled.

**Comment by jmcdaniels** [comment]
Step numbers added.
