### ISSUE TITLE
Be consistent when calling out steps

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#23]
https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L1018
Here it said "step 3", while here:
https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L1030
it says "Step <span>#</span>1"

The second one looks better and should be used consistently.

**Comment by jmcdaniels** [comment]
The better looking one will be used throughout.
