### ISSUE TITLE
How would you handle a key stored in a protected non-volatile location?

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#24]
https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L1022

In test #3, if the key is stored in something like a TEE on a mobile device, this is non-volatile storage but it not accessible to the main OS. How would this type of situation be handled? Would the test be "passed" without a specific test as long as there is a sufficient description in the TSS?

This is a general question, not a specific target, but a question about how to handle interactions between a rich OS and a restricted OS. for the destruction of key materials.

**Comment by jmcdaniels** [comment]
This situation should fall under "Tests 3 and 4 do not apply for the selection instructing the underlying platform to destroy the representation of the key, as the TOE has no visibility into the inner workings and completely relies on the underlying platform."
