### ISSUE TITLE
KMD should probably be noted other than in EA

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#25]
https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L1062
This is the first mention of a Key Management Description as a separate document. To date proprietary information has been handled either in separate docs as needed or with dual versions of a Security Target providing protected information marked for removal before publication (so there are public and proprietary versions). 

I am not sure there should be anything other than the TSS requirement for consistency with other PPs, but if this is really expected, then it should be described somewhere else (preferably before getting to it in the EA).

A note that proprietary information can be removed from the final, public copy of the ST would likely be sufficient here (but is a general comment, not specific to just this requirement).

Is the KMD actually a document intended from the Management server?

**Comment by woodbe** [comment]
FDP_PM_EXT.1 EA explicitly calls for the KMD to be used and calls out specifically content to be placed in the KMD vs the TSS.

**Comment by jmcdaniels** [comment]
The goal is to align with the FDE cPP in this matter.  That determined specific key management is expected to be proprietary and should be in a specific additional document containing a certain set of information that should be reviewed.

I did address to formatting to be more consistent and better aligned with the FDE.

**Comment by woodbe** [comment]
Can you add KMD to the acronyms at the end of the document? The TSS is listed there, it would be helpful to have the reference somewhere other than just in the EA.

**Comment by jmcdaniels** [comment]
I realized the appendix in the FDE is not included and that is probably causing confusion on this issue. There will be an additional opportunity to comment on this.

**Comment by woodbe** [comment]
That would explain it, I have browsed through the FDE PPs, but I haven't read them to the extent of actually planning an evaluation from them, so the appendices haven't really been my focus. I completely understand the point of the KMD, it was just unconnected to any expectation, so if you weren't familiar with what was being asked, you would likely be confused.

**Comment by jmcdaniels** [comment]
I am working on adding it right now to the FE draft, it should be up shortly.

**Comment by jmcdaniels** [comment]
KMD is now included, closing comment.  Feel free to create new specific comments on appendix.
