### ISSUE TITLE
FCS_VAL_EXT.1.3 when authorization is handled separate from TOE

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#26]
Depending on the implementation and integration level between the software and the OS, the software may depend on authentication from the OS to determine the validity of the user's credentials. In this case, successful credentials are passed to the software without needing to be checked individually. This is not to say not to protect the keys (such as key wrap), but that the only credentials passed to the software have already been validated by the platform, and so unless there is something "wrong" on the system (like a MitM or other integrity problem) or the stored key itself has been corrupted (like a storage failure), there is no way for the software to actually have a verification as described here (at least logically).

In this scenario I would expect the OS (or whatever authentication framework is used) to verify the credentials and pass them properly to the software where they would be used. If the user is not validated (i.e. they enter the wrong credential information), the software never finds out because "bad" credentials are never passed to the system to try.

I am not sure how exactly to modify this requirement, other than maybe making FCS_VAL_EXT.1.3 a selection-based requirement dependent on how authorization is handled (by the platform or by the TOE).

**Comment by woodbe** [comment]
Another question I have based on this requirement (on re-reading it) is why are the FEKs the keys that have to be destroyed in the first selection? 

This implies that the FE application is going to go to each file and individually delete its keys (since in most cases the FEK is likely to be associated with the file itself and not stored in some single central database). It would seem like the root keys are what should be deleted, since then the FEKs can't be recovered (and hence the file can't be recovered). 

Depending on what selections are made in FCS_KYC_EXT.1, the FEK may be chained to a KEK (or directly derived), so it would seem that if I can break the chain by clearing the KEK, that it would meet the same requirement.

**Comment by jmcdaniels** [comment]
Making it selection dependent off of the AUT requirement, the platform should perform validation if handling auth.

For the second question, that is already permitted per FCS_CKM_EXT.4 which defines destruction methods:

"For non-volatile memory that consists of [selection:
destruction of all key encrypting keys protecting the target key, where none of the KEKs protecting the target key are derived ,"
