### ISSUE TITLE
FDP_PRT_EXT.1.2 EA redundant steps

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#27]
Steps 4-7 in the test would seem to be redundant. In the first steps you create the file with the string and verify that the string is not available in non-volatile memory after closing the file. What additional purpose is served by opening the file again and seeing that the string is in memory? 

Based on the requirement it isn't clear that having the string in memory twice is a problem (that is not explicitly stated as a failure, so if there was a copy for the editor and one for the FE app, that would seem to be OK while the file is open, such as garbage collection not having completed yet maybe), so what purpose is being serviced by these steps?

**Comment by jmcdaniels** [comment]
One of these should have been non-volatile.  Fixed the test now one search of non-volatile and one dumb of volatile.  Removed the search for the string in volatile as it provides little value.
