### ISSUE TITLE
FDP_PRT_EXT.2.1 EA Test 1 description does not match requirement

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#28]
In the EA for this requirement (https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L1474-L147

the test case talks about shared files and access. This EA does not make sense in terms of the requirement about clearing temporary data. Further, the actual test steps listed later do not have any test steps that use multiple users, but only the creation of a new document and editing a document and checking for the contents. 

It seems the test description here should be removed (or tests for multiple users should be added though it is not clear how that would actually help with assurance since there should not be differences between users accessing the encrypted files).

**Comment by jmcdaniels** [comment]
Test removed.  Added line in the other test to repeat test with shared file if supported.
