### ISSUE TITLE
FMT_SMF.1.1(2) cryptographic erase function

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#29]
For the selection https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L1637
is this expected to be triggered by user actions (such as a configuration for FCS_VAL_EXT.1.3) or by admin command (i.e. in some way the admin should be able to say "wipe the protected files")?

This almost seems like a command for the FE Management server, but the specific intent or expectation here isn't clear.

As a question on this, on a stand alone install, is it expected that this would be triggered by say uninstalling the application (as opposed to some UI interface where the user/admin says to wipe)? Some additional guidance in the Application Note would be helpful.

**Comment by jmcdaniels** [comment]
There is no guarantee of a management server. If the FE EM is included and part of the ST then that should be acceptable.

On a stand alone install this functionality is expected to be possible by some user, either admin or user.  The method is up to the vendor and certainly could be done by uninstall.

Added to the app note "This function should be able to be triggered by a user or admin and may be triggered by uninstallation."
