### ISSUE TITLE
FIA_FCT_EXT.1 Application Note seems to add new requirement

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#30]
This requirement states that the TOE would support multiple, separate users, with their own KEKs, and then says they can have shared keys. The application note then explicitly states the users need to be able to have non-shared files. 

https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L1825-L1830

This is what I would actually expect from a system that supports multiple users (that they would be able to have non-shared files, sharing is actually the "extra" thing here). The way the requirement reads though makes it seem that multi-user must be sharing, and then the note states that it needs to be both. Stating that users get unique KEKs is not enough to be clear they can have files that aren't shared.

To be completely clear, I would actually say this should be split into two requirements, 

FIA_FCT_EXT.1 Extended: Multi-User Authentication
FIA_FCT_EXT.2 Extended: Authorized Key Sharing

FIA_FCT_EXT.1 would have the existing FIA_FCT_EXT.1.1 as well as a new FIA_FCT_EXT.1.2:

_The TSF shall support the ability of each user to have files protected by a key chain tied only to that user's credentials._

The second requirement would map to FIA_FCT_EXT.1.2.

This would make it completely clear exactly what is intended by making sure that the ability to have individual files (and not shared) is handled on its own, and then as an addition it may be possible to also share files in this environment (since FIA_FCT_EXT.2 would be hierarchical to FIA_FCT_EXT.1).

**Comment by jmcdaniels** [comment]
I agree, sharing and multi-user should be separate independent requirements.  I agree that unique KEKs is insufficient and the new proposed 1.2 should be included.
