### ISSUE TITLE
FCS_CKM_EXT.5 EA clarification

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#35]
Technically this statement is correct https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L2225
that the protection of the FAK is covered by FCS_COP.1(5), but explicitly it is covered by FCS_COP_EXT.1(6) which points to FCS_COP.1(5). To be completely correct the FCS_COP_EXT.1(6) should either replace the existing text or it should be added with something like 

_protection of the FAK itself is covered by FCS_COP.1(5) **via FCS_COP_EXT.1(6)**_

**Comment by jmcdaniels** [comment]
Just changed to (6), to align with SFR.
