### ISSUE TITLE
FCS_CKM_EXT.1.1(1) maximum length for password support

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#36]
The requirement here states that the password/passphrase must support at least 64 characters as the smallest maximum length value allowed. This requirement does not make sense for mobile platforms on which FE apps may be deployed. Asking someone to enter a password anywhere close to this length on a soft, screen keyboard is not practical (even 20 characters is considered too long for that type of entry). Further, the Android platform itself only supports a maximum of 16 characters, so any product reliant on parts of the Android framework (so as to not duplicate functionality) will not be able to meet this requirement.

This requirement could be modified to support specific targets (i.e. mobile devices are allowed a smaller max while non-mobile would still be subject to the 64 character minimum).

**Comment by jmcdaniels** [comment]
Updated to allow platform defined length if platform is leveraged.  If app implemented there is no reason to have a smaller limit, it may not be practical for the far majority of end users to use a password that long, but this requirement is just defining maximum support. 

Also updated PBKDF iterations to be lower if platform is chosen, as some platforms still have lower iteration counts.  Still require minimum of 1000 as recommended by NIST.  

These changes were not made to the FE EM module, as they do not have mobile restrictions.  This may be reconsidered for specific examples in the future.
