### ISSUE TITLE
FCS_COP.1(8) requires RSA 3072

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#37]
Is there a reason that the key size is fixed at 3027 instead of being a selection of 3072 or 4096?
https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L2498

In [TD0263](https://www.niap-ccevs.org/Documents_and_Guidance/view_td.cfm?td_id=269) which talked about key wrapping in the older EP it was allowed to select either key size, so I am curious as to why 3072 is not being specified as the only option.

Even the TSS description of the expected documentation states that if multiple methods and key sizes are supported.

**Comment by jmcdaniels** [comment]
Added 4096, all such selections are now 3072, 4096.
