### ISSUE TITLE
FCS_VAL_EXT change

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#39]
In #26 you moved the entire requirement to selection based, but I think what really needs to happen (thinking about it now), is that FCS_VAL_EXT.1.3 should become a new, separate requirement. 

FCS_VAL_EXT.1.1/2 are both about the validation of keys before being used, how it is protected and that it must be done before being used. Since this covers most of the KEKs and the FEKs, it would seem that these should be mandatory. I don't know if all FEKs could be derived from something passed from the platform, it would seem that the platform would hand off a "master key" to protect FEKs or some sort of intermediate KEKs, and at that point, any KEKs or FEKs should be protected and validated according to 1/2 here.

But if the platform is performing the authorization, then FCS_VAL_EXT.1.3 potentially becomes a problem because this is basically what to do when there is a failed login. Looking at the MDFPP, the outcome for failed authentication is handled by FIA_AFL_EXT.1, which is very long and has requirements not relevant here, but my point being that failed authorization is handled in a separate requirement.

I would do the following:

- FCS_VAL_EXT.1 Validation -> FCS_VAL_EXT.1 Key Validation
- FCS_VAL_EXT.1.3 -> FCS_VAL_EXT.2 Validation Failure
- FCS_VAL_EXT.2.1 = FCS_VAL_EXT.1.3 (so the requirement itself doesn't change)

The EA for the new FCS_VAL_EXT.1 would be a description in the TSS about how the keys are validated (which is the current TSS description part of the EA). There would be no tests associated here and likely no guidance requirement.

The existing guidance and testing portions of the EA would become the EA for FCS_VAL_EXT.2 with a new section on the TSS to review the description about how the TOE determines and maintains a count for unsuccessful validations and the actions that are taken.

**Comment by woodbe** [comment]
The new FCS_VAL_EXT.1 could be either selection or mandatory, but I think it should be mandatory with a note that if the platform is doing verification of the user credentials that a key protected by the platform may not be included in the TOE-protected keys (and that this should be clearly described).

**Comment by jmcdaniels** [comment]
I am thinking that is adding a fair bit of compexity for the value is provides.  I agree that we could seperate remediation out, but I think if the platform is handling the auth you are also going to having it handle the validation and remediation.

For the detail on protected keys, I agree platform performing these functions means the potential for platform key storage.  I think the most appropriate place to note that is in the KYC and KYP requirements.

**Comment by woodbe** [comment]
So the question is about the validation. If you are supposed to validate all the keys (which is what I would assume), then the platform is likely to only verify one of them, not all of them. Here is an example of what I am thinking of:

Password -> KDF -> protect a root FE key (i.e. a root KEK) -> folder KEK -> FEK

Here the password is run through a KDF and the result is used to encrypt the root KEK. The root KEK is then used to encrypt the folder KEKs (say one for each separate folder) which is then used to encrypt the FEKs. Obviously I'm simplifying here a little, there would be other data involved (tweaks, IVs, maybe even hardware keys, but this should suffice).

If the software implements its own authentication service, then all this is handled by the software, and it is fine. The password will be validated by the software as should all the rest of the keys in the hierarchy.

In the case I'm talking about though, the authentication service is provided by the platform (say a Windows Hello login or the Android lock screen). Here the OS validates the password (or smart card, whatever is being used). The OS then passes a secret on to the application. This can be the password, it would be some other key, something that is associated with the user (for example the software could have established something where-in when the user authenticates it unlocks some string/key that is provided as input to the app) what it is doesn't really matter). The key point here though is that the OS has performed the validation of the user, and only then does it pass the secret on. So the application never needs to validate the user authentication input because it only gets input on success.

Further down though, the KEKs and the FEKS, I read the requirement as intended for the application to perform validation of the keys in some way to ensure they are correct. For example a key wrap or AES-GCM (something in FCS_COP.1(5)), and that this must be done when those keys are unwrapped to ensure they haven't been tampered with (or just corrupted). At this point the OS is no longer directly involved, the key storage at this level is up to the application, so the KEKs and FEKs need to be validated by the application.

So I don't see how the KEKs and FEKs can rely on the OS like you can for the authentication data, and it would seem to me that they are mandatory for the application. So an application that relies on the OS to provide authentication basically doesn't have to validate the keys that are stored, which is how I see this being selected (or not) in practice.

**Comment by jmcdaniels** [comment]
Reading this over and thinking about it some more, the real goal is not validation of all keys.  The goal is that validation is expected to happen somewhere and when it does we need to make sure it is done in an acceptable way.  I would expect most products to just rely on platform to do this check, but in cases where they may also implement something to ensure what they receive from that platform is valid the requirement should reflect that.  

So upon further reflection I concur with your recommendation.

**Comment by jmcdaniels** [comment]
Updated requirements, if any other concerns with the requirement please indicate them now.

**Comment by woodbe** [comment]
This looks good to me. Not exactly how I thought you would do it, but it looks good, so I don't see any issues with this update.
