### ISSUE TITLE
Clarifying FMT_SMF.1.1(2) activities section for password/passphrase complexity

### ISSUE THREAD

**Issue by thibodux** [commoncriteria/fileencryption#5]
In the activities section of the new FMT_SMF.1.1(2) requirement, I think there is a small need to clarify the requirement for the password/passphrase complexity setting.

I am specifically looking at the wording here https://github.com/commoncriteria/fileencryption/blob/master/input/fileencryption.xml#L1677 that says 

> If password or passphrase authorization factors are implemented by the TOE, then the appropriate "change" selection must be included.

Reading this statement by itself, I interpret to say that the TOE must implement a management function to support a configurable complexity setting for the password / passphrase if the TOE implements any password/passphrase authorization.

However, earlier in the PP in the Application note for FCS_CKM_EXT.1.5(1), the text says

> For FCS_CKM_EXT.1.4(1) If the minimum password length is settable, then ST author chooses "a value settable by the administrator for this component, as well as the "configure password/passphrase complexity setting" item for FMT_SMF.2. If the minimum length is not settable, the ST author fills in the assignment with the minimum length the password must be (zero-length passwords are not allowed for compliant TOEs). 

Which I read as saying that the management function is optional and only applies if the complexity is in fact configurable.

I would assume the latter interpretation is the intended requirement, but please clarify if that is the incorrect interpretation. If my interpretation is correct, then I would think the text for new requirement FMT_SMF.1.1(2) should be a bit more precise, such as

> If password or passphrase authorization factors are implemented by the TOE and their complexity is configurable, then the appropriate "change" selection must be included.

**Comment by jmcdaniels** [comment]
In alignment with NIST SP 800-63, I am removing all requirements surrounding complexity except for supported characters.

**Comment by thibodux** [comment]
Thanks for following up.
