### ISSUE TITLE
Should the platform be required to meet MDFPP?

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/fileencryption#9]
In the description of the operational guidance there is a specific reference that the mobile device needs to be able to be configured according to the MDFPP (https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L158 and https://github.com/commoncriteria/fileencryption/blob/4dde142afe4327a157a32f8e454f7de703a95add/input/fileencryption.xml#L159).

Since the TOEs are supposed to be independent of the platform, I don't see how you can specify the MDFPP here (and not, say the GPOS PP for non-mobile).

**Comment by jmcdaniels** [comment]
Removed.
